#ifndef HCONFIG_H_
#define HCONFIG_H_

#define FAST_BUILD
#define CMAKE_BUILD_TYPE "RELEASE"
#define CMAKE_INSTALL_PREFIX "/usr/local"
/* #undef HIGHSINT64 */
/* #undef HIGHS_HAVE_MM_PAUSE */
#define HIGHS_HAVE_BUILTIN_CLZ
/* #undef HIGHS_HAVE_BITSCAN_REVERSE */

#define HIGHS_GITHASH "006c08c5a-dirty"
#define HIGHS_COMPILATION_DATE "2023-12-17"
#define HIGHS_VERSION_MAJOR 1
#define HIGHS_VERSION_MINOR 6
#define HIGHS_VERSION_PATCH 0
#define HIGHS_DIR ""

#endif /* HCONFIG_H_ */
